### ISSUE TITLE
Pointer events might get stuck when using `async` mode

### ISSUE THREAD

**Issue by mmomtchev** [mmomtchev/react-native-settings#76]
```
PASS test/sync.test.tsx (7.59 s)
FAIL test/async.test.tsx
  ● async › set a boolean element

    expect(received).toMatchSnapshot()

    Snapshot name: `async set a boolean element 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -5,[11](https://github.com/mmomtchev/react-native-settings/actions/runs/6071602826/job/16469954741#step:5:12) +5,11 @@
            "padding": 5,
          }
        }
      >
        <View
    -     pointerEvents="auto"
    +     pointerEvents="none"
          style={
            Object {
              "flex": 1,
              "opacity": 1,
            }

      104 |
      105 |         expect(r.UNSAFE_queryAllByType(Switch)[0].props.value).toBe(true);
    > 106 |         expect(r.toJSON()).toMatchSnapshot();
          |                            ^
      107 |
      108 |         expect(newSettings[2].get).toHaveBeenCalledTimes(1);
      109 |         expect(newSettings[2].set).toHaveBeenCalledTimes(1);

      at Object.<anonymous> (test/async.test.tsx:106:28)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:[22](https://github.com/mmomtchev/react-native-settings/actions/runs/6071602826/job/16469954741#step:5:23):9)
```

**Comment by mmomtchev** [comment]
Appears to be timing-related and difficult to reproduce
